name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build DotNet
      run: dotnet build ./SfdScriptUtil -f net461
      
      
    - name: Create Release
      uses: SierraSoftworks/gh-releases@v1.0.7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        overwrite: 'true'
        files: |
          SfdScriptUtil\bin\Debug\scriptutil.exe
